#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("Busidex.Presentation.Android.Resource", IsApplication=true)]

namespace Busidex.Presentation.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public const int buttonFontColor = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int labelFontColor = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int layoutBackground = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int listBackground = 2130968579;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int delete = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon_2x = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int large_logo = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int people = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int spotlight_icon = 2130837509;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06000e
			public const int btnConnect = 2131099662;
			
			// aapt resource value: 0x7f060005
			public const int btnLogin = 2131099653;
			
			// aapt resource value: 0x7f06000b
			public const int btnMyBusidex = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int btnMyOrganizations = 2131099660;
			
			// aapt resource value: 0x7f06000a
			public const int btnSearch = 2131099658;
			
			// aapt resource value: 0x7f06000f
			public const int btnStart = 2131099663;
			
			// aapt resource value: 0x7f060007
			public const int imageView1 = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int imageView2 = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int imageView3 = 2131099657;
			
			// aapt resource value: 0x7f060012
			public const int imgCard = 2131099666;
			
			// aapt resource value: 0x7f060006
			public const int imgLogo = 2131099654;
			
			// aapt resource value: 0x7f06000d
			public const int lstCards = 2131099661;
			
			// aapt resource value: 0x7f060000
			public const int relativeLayout1 = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int textView1 = 2131099649;
			
			// aapt resource value: 0x7f060003
			public const int textView2 = 2131099651;
			
			// aapt resource value: 0x7f060011
			public const int txtCompanyName = 2131099665;
			
			// aapt resource value: 0x7f060010
			public const int txtName = 2131099664;
			
			// aapt resource value: 0x7f060004
			public const int txtPassword = 2131099652;
			
			// aapt resource value: 0x7f060002
			public const int txtUserName = 2131099650;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Login = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int MyBusidex = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int MyOrganizations = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Search = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int StartUp = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int UserCardListItem = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f05000c
			public const int Global_LoadingCards = 2131034124;
			
			// aapt resource value: 0x7f05000b
			public const int Login_btnLogin = 2131034123;
			
			// aapt resource value: 0x7f05000a
			public const int Login_lblPassword = 2131034122;
			
			// aapt resource value: 0x7f050009
			public const int Login_lblUserName = 2131034121;
			
			// aapt resource value: 0x7f050007
			public const int Main_btnMyBusidex = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int Main_btnMyOrganizations = 2131034120;
			
			// aapt resource value: 0x7f050006
			public const int Main_btnSearch = 2131034118;
			
			// aapt resource value: 0x7f050003
			public const int StartPage_btnConnect = 2131034115;
			
			// aapt resource value: 0x7f050005
			public const int StartPage_btnStart = 2131034117;
			
			// aapt resource value: 0x7f050002
			public const int StartPage_lblAlreadyAUser = 2131034114;
			
			// aapt resource value: 0x7f050004
			public const int StartPage_lblNewUser = 2131034116;
			
			// aapt resource value: 0x7f050001
			public const int StartPage_lblWelcome = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
