#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("Busidex.Presentation.Android.Resource", IsApplication=true)]

namespace Busidex.Presentation.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int SlideAnimation = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int SlideOutAnimation = 2130968577;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050000
			public const int buttonFontColor = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int labelFontColor = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int layoutBackground = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int listBackground = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int primaryLabelColor = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int textInputColor = 2131034117;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int add = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int browser = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int checkmark = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int delete = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int email = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Exit = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int fb = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int icon = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int Icon_2x = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int large_logo = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int maps = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int notes = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int people = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int phone = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int red_minus = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int remove = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int share = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int splash = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int splash2 = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int spotlight_icon = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int sync = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int twitter = 2130837525;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080066
			public const int btnAccept = 2131230822;
			
			// aapt resource value: 0x7f08006b
			public const int btnConnect = 2131230827;
			
			// aapt resource value: 0x7f080067
			public const int btnDecline = 2131230823;
			
			// aapt resource value: 0x7f080009
			public const int btnHideInfo = 2131230729;
			
			// aapt resource value: 0x7f080074
			public const int btnInfo = 2131230836;
			
			// aapt resource value: 0x7f080010
			public const int btnLogin = 2131230736;
			
			// aapt resource value: 0x7f080019
			public const int btnLogout = 2131230745;
			
			// aapt resource value: 0x7f080017
			public const int btnMyBusidex = 2131230743;
			
			// aapt resource value: 0x7f080018
			public const int btnMyOrganizations = 2131230744;
			
			// aapt resource value: 0x7f08003b
			public const int btnOrgDetails = 2131230779;
			
			// aapt resource value: 0x7f080039
			public const int btnOrgInfo = 2131230777;
			
			// aapt resource value: 0x7f08003c
			public const int btnOrgMembers = 2131230780;
			
			// aapt resource value: 0x7f08003d
			public const int btnOrgReferrals = 2131230781;
			
			// aapt resource value: 0x7f080035
			public const int btnOrganizationFacebook = 2131230773;
			
			// aapt resource value: 0x7f080034
			public const int btnOrganizationTwitter = 2131230772;
			
			// aapt resource value: 0x7f080033
			public const int btnOrganizationWeb = 2131230771;
			
			// aapt resource value: 0x7f080008
			public const int btnPanelAdd = 2131230728;
			
			// aapt resource value: 0x7f080004
			public const int btnPanelBrowser = 2131230724;
			
			// aapt resource value: 0x7f080003
			public const int btnPanelEmail = 2131230723;
			
			// aapt resource value: 0x7f080001
			public const int btnPanelMap = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int btnPanelNotes = 2131230722;
			
			// aapt resource value: 0x7f080005
			public const int btnPanelPhone = 2131230725;
			
			// aapt resource value: 0x7f080007
			public const int btnPanelRemove = 2131230727;
			
			// aapt resource value: 0x7f080006
			public const int btnPanelShare = 2131230726;
			
			// aapt resource value: 0x7f080048
			public const int btnPhoneNumber = 2131230792;
			
			// aapt resource value: 0x7f080025
			public const int btnSaveNotes = 2131230757;
			
			// aapt resource value: 0x7f080052
			public const int btnSaveProfile = 2131230802;
			
			// aapt resource value: 0x7f080016
			public const int btnSearch = 2131230742;
			
			// aapt resource value: 0x7f08001b
			public const int btnSettings = 2131230747;
			
			// aapt resource value: 0x7f08005e
			public const int btnShareCard = 2131230814;
			
			// aapt resource value: 0x7f08001c
			public const int btnSharedCardsNotification = 2131230748;
			
			// aapt resource value: 0x7f08006d
			public const int btnStart = 2131230829;
			
			// aapt resource value: 0x7f08001a
			public const int btnSync = 2131230746;
			
			// aapt resource value: 0x7f080014
			public const int imgBusidexIcon = 2131230740;
			
			// aapt resource value: 0x7f08000a
			public const int imgCardDetail = 2131230730;
			
			// aapt resource value: 0x7f080072
			public const int imgCardHorizontal = 2131230834;
			
			// aapt resource value: 0x7f080073
			public const int imgCardVertical = 2131230835;
			
			// aapt resource value: 0x7f08005d
			public const int imgCheckShared = 2131230813;
			
			// aapt resource value: 0x7f08006e
			public const int imgLoginLogo = 2131230830;
			
			// aapt resource value: 0x7f080011
			public const int imgLogo = 2131230737;
			
			// aapt resource value: 0x7f080027
			public const int imgNotesCardHorizontal = 2131230759;
			
			// aapt resource value: 0x7f080028
			public const int imgNotesCardVertical = 2131230760;
			
			// aapt resource value: 0x7f080026
			public const int imgNotesSaved = 2131230758;
			
			// aapt resource value: 0x7f080015
			public const int imgOrgIcon = 2131230741;
			
			// aapt resource value: 0x7f08003f
			public const int imgOrganizationHeaderImage = 2131230783;
			
			// aapt resource value: 0x7f080038
			public const int imgOrganizationThumbnail = 2131230776;
			
			// aapt resource value: 0x7f080043
			public const int imgPhoneCardHorizontal = 2131230787;
			
			// aapt resource value: 0x7f080044
			public const int imgPhoneCardVertical = 2131230788;
			
			// aapt resource value: 0x7f080050
			public const int imgProfileEmailSaved = 2131230800;
			
			// aapt resource value: 0x7f080051
			public const int imgProfilePasswordSaved = 2131230801;
			
			// aapt resource value: 0x7f080068
			public const int imgResults = 2131230824;
			
			// aapt resource value: 0x7f080013
			public const int imgSearchIcon = 2131230739;
			
			// aapt resource value: 0x7f08005b
			public const int imgShareHorizontal = 2131230811;
			
			// aapt resource value: 0x7f08005c
			public const int imgShareVertical = 2131230812;
			
			// aapt resource value: 0x7f080064
			public const int imgSharedCardHorizontal = 2131230820;
			
			// aapt resource value: 0x7f080065
			public const int imgSharedCardVertical = 2131230821;
			
			// aapt resource value: 0x7f08002a
			public const int ingOrgDetailLogoBanner = 2131230762;
			
			// aapt resource value: 0x7f08006a
			public const int lblAlreadyAUser = 2131230826;
			
			// aapt resource value: 0x7f08002b
			public const int lblContacts = 2131230763;
			
			// aapt resource value: 0x7f08002c
			public const int lblEmail = 2131230764;
			
			// aapt resource value: 0x7f080053
			public const int lblEmailError = 2131230803;
			
			// aapt resource value: 0x7f08002e
			public const int lblFax = 2131230766;
			
			// aapt resource value: 0x7f080069
			public const int lblIntro = 2131230825;
			
			// aapt resource value: 0x7f08006c
			public const int lblNewUser = 2131230828;
			
			// aapt resource value: 0x7f08000e
			public const int lblPassword = 2131230734;
			
			// aapt resource value: 0x7f080054
			public const int lblPasswordError = 2131230804;
			
			// aapt resource value: 0x7f08002d
			public const int lblPhone = 2131230765;
			
			// aapt resource value: 0x7f080047
			public const int lblPhoneNumberType = 2131230791;
			
			// aapt resource value: 0x7f08004c
			public const int lblProfileEmail = 2131230796;
			
			// aapt resource value: 0x7f080049
			public const int lblProfileHeader = 2131230793;
			
			// aapt resource value: 0x7f08004e
			public const int lblProfilePassword = 2131230798;
			
			// aapt resource value: 0x7f080059
			public const int lblShareDescription = 2131230809;
			
			// aapt resource value: 0x7f08005f
			public const int lblShareError = 2131230815;
			
			// aapt resource value: 0x7f080058
			public const int lblShareTitle = 2131230808;
			
			// aapt resource value: 0x7f08000c
			public const int lblUserName = 2131230732;
			
			// aapt resource value: 0x7f08001e
			public const int linearLayout1 = 2131230750;
			
			// aapt resource value: 0x7f08006f
			public const int listItemLayout = 2131230831;
			
			// aapt resource value: 0x7f08000b
			public const int loginLayout = 2131230731;
			
			// aapt resource value: 0x7f080021
			public const int lstCards = 2131230753;
			
			// aapt resource value: 0x7f080041
			public const int lstOrganizationMembers = 2131230785;
			
			// aapt resource value: 0x7f080022
			public const int lstOrganizations = 2131230754;
			
			// aapt resource value: 0x7f080045
			public const int lstPhoneNumbers = 2131230789;
			
			// aapt resource value: 0x7f080056
			public const int lstSearchResults = 2131230806;
			
			// aapt resource value: 0x7f080060
			public const int lstSharedCards = 2131230816;
			
			// aapt resource value: 0x7f080012
			public const int mainLayout = 2131230738;
			
			// aapt resource value: 0x7f08003a
			public const int orgButtonContainer = 2131230778;
			
			// aapt resource value: 0x7f080037
			public const int orgLayout = 2131230775;
			
			// aapt resource value: 0x7f08003e
			public const int orgMemberLayout = 2131230782;
			
			// aapt resource value: 0x7f080029
			public const int organizationLayout = 2131230761;
			
			// aapt resource value: 0x7f080000
			public const int panelLayout = 2131230720;
			
			// aapt resource value: 0x7f080042
			public const int phoneLayout = 2131230786;
			
			// aapt resource value: 0x7f080046
			public const int phoneNumberEntryLayout = 2131230790;
			
			// aapt resource value: 0x7f08004b
			public const int profileLayout = 2131230795;
			
			// aapt resource value: 0x7f080023
			public const int relativeLayout1 = 2131230755;
			
			// aapt resource value: 0x7f080057
			public const int shareCardLayout = 2131230807;
			
			// aapt resource value: 0x7f080061
			public const int sharedCardListItemLayout = 2131230817;
			
			// aapt resource value: 0x7f080071
			public const int txtCompanyName = 2131230833;
			
			// aapt resource value: 0x7f08002f
			public const int txtContacts = 2131230767;
			
			// aapt resource value: 0x7f080030
			public const int txtEmail = 2131230768;
			
			// aapt resource value: 0x7f080032
			public const int txtFax = 2131230770;
			
			// aapt resource value: 0x7f08001f
			public const int txtFilter = 2131230751;
			
			// aapt resource value: 0x7f080020
			public const int txtFilter1 = 2131230752;
			
			// aapt resource value: 0x7f080070
			public const int txtName = 2131230832;
			
			// aapt resource value: 0x7f080024
			public const int txtNotes = 2131230756;
			
			// aapt resource value: 0x7f08001d
			public const int txtNotificationCount = 2131230749;
			
			// aapt resource value: 0x7f08000f
			public const int txtPassword = 2131230735;
			
			// aapt resource value: 0x7f080031
			public const int txtPhone = 2131230769;
			
			// aapt resource value: 0x7f08004a
			public const int txtProfileDescription = 2131230794;
			
			// aapt resource value: 0x7f08004d
			public const int txtProfileEmail = 2131230797;
			
			// aapt resource value: 0x7f08004f
			public const int txtProfilePassword = 2131230799;
			
			// aapt resource value: 0x7f080055
			public const int txtSearch = 2131230805;
			
			// aapt resource value: 0x7f080040
			public const int txtSearchOrgMembers = 2131230784;
			
			// aapt resource value: 0x7f08005a
			public const int txtShareEmail = 2131230810;
			
			// aapt resource value: 0x7f080063
			public const int txtSharedCardCompanyName = 2131230819;
			
			// aapt resource value: 0x7f080062
			public const int txtSharedCardName = 2131230818;
			
			// aapt resource value: 0x7f08000d
			public const int txtUserName = 2131230733;
			
			// aapt resource value: 0x7f080036
			public const int vwWeb = 2131230774;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ButtonPanel = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Card = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Login = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int MyBusidex = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int MyOrganizations = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Notes = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Organization = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int OrganizationListItem = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int OrganizationMembers = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int Phone = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int PhoneNumberEntry = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int Profile = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int Search = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int SharedCard = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int SharedCardList = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int SharedCardListItem = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int Splash = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int StartUp = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int UserCardListItem = 2130903059;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f06000d
			public const int Global_LoadingCards = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int Global_LoadingCardsProgress = 2131099662;
			
			// aapt resource value: 0x7f06000c
			public const int Global_OneMoment = 2131099660;
			
			// aapt resource value: 0x7f06000b
			public const int Login_btnLogin = 2131099659;
			
			// aapt resource value: 0x7f06000a
			public const int Login_lblPassword = 2131099658;
			
			// aapt resource value: 0x7f060009
			public const int Login_lblUserName = 2131099657;
			
			// aapt resource value: 0x7f060007
			public const int Main_btnMyBusidex = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int Main_btnMyOrganizations = 2131099656;
			
			// aapt resource value: 0x7f060006
			public const int Main_btnSearch = 2131099654;
			
			// aapt resource value: 0x7f060017
			public const int Notes_Save = 2131099671;
			
			// aapt resource value: 0x7f060018
			public const int Organization_NoOrganizations = 2131099672;
			
			// aapt resource value: 0x7f06001e
			public const int Profile_DescriptionNewAccount = 2131099678;
			
			// aapt resource value: 0x7f06001f
			public const int Profile_DescriptionUpdateAccount = 2131099679;
			
			// aapt resource value: 0x7f06001c
			public const int Profile_ErrorAccountExists = 2131099676;
			
			// aapt resource value: 0x7f06001d
			public const int Profile_ErrorAccountGeneral = 2131099677;
			
			// aapt resource value: 0x7f06001a
			public const int Profile_ErrorEmailGeneral = 2131099674;
			
			// aapt resource value: 0x7f060019
			public const int Profile_ErrorEmailInUse = 2131099673;
			
			// aapt resource value: 0x7f06001b
			public const int Profile_ErrorUnableToCreateAccount = 2131099675;
			
			// aapt resource value: 0x7f060015
			public const int Share_ConfirmAccept = 2131099669;
			
			// aapt resource value: 0x7f060016
			public const int Share_ConfirmDecline = 2131099670;
			
			// aapt resource value: 0x7f060013
			public const int Share_ConfirmShareTitleAccept = 2131099667;
			
			// aapt resource value: 0x7f060014
			public const int Share_ConfirmShareTitleDecline = 2131099668;
			
			// aapt resource value: 0x7f060010
			public const int Share_Description = 2131099664;
			
			// aapt resource value: 0x7f060012
			public const int Share_Error = 2131099666;
			
			// aapt resource value: 0x7f060011
			public const int Share_ShareCard = 2131099665;
			
			// aapt resource value: 0x7f06000f
			public const int Share_Title = 2131099663;
			
			// aapt resource value: 0x7f060003
			public const int StartPage_btnConnect = 2131099651;
			
			// aapt resource value: 0x7f060005
			public const int StartPage_btnStart = 2131099653;
			
			// aapt resource value: 0x7f060002
			public const int StartPage_lblAlreadyAUser = 2131099650;
			
			// aapt resource value: 0x7f060004
			public const int StartPage_lblNewUser = 2131099652;
			
			// aapt resource value: 0x7f060001
			public const int StartPage_lblWelcome = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int app_name = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int Theme_Splash = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
