#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("Busidex.Presentation.Droid.v2.Resource", IsApplication=true)]

namespace Busidex.Presentation.Droid.v2
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::ModernHttpClient.Resource.String.library_name = global::Busidex.Presentation.Droid.v2.Resource.String.library_name;
			global::BranchXamarinSDK.Droid.Resource.String.library_name = global::Busidex.Presentation.Droid.v2.Resource.String.library_name;
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int MyBusidexIconStart = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int ResizeHorizontal = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int ResizeVertical = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int Rotate = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int SlideAnimation = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int SlideAnimationFast = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int SlideDownAnimation = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int SlideOutAnimation = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int SlideOutAnimationFast = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int SlideUpAnimation = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int Spin = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int Zoom = 2130968587;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Animator
		{
			
			// aapt resource value: 0x7f050000
			public const int SlideAnimation = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int SlideAnimationFast = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int SlideDownAnimation = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int SlideOutAnimation = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int SlideOutAnimationFast = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int SlideUpAnimation = 2131034117;
			
			static Animator()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animator()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010001
			public const int civ_border_color = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int civ_border_overlay = 2130771970;
			
			// aapt resource value: 0x7f010000
			public const int civ_border_width = 2130771968;
			
			// aapt resource value: 0x7f010003
			public const int civ_fill_color = 2130771971;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f070000
			public const int buttonFontColor = 2131165184;
			
			// aapt resource value: 0x7f07000b
			public const int buttonMuted = 2131165195;
			
			// aapt resource value: 0x7f07000a
			public const int buttonSuccess = 2131165194;
			
			// aapt resource value: 0x7f070001
			public const int buttonWhite = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int labelFontColor = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int labelFontColorDark = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int layoutBackground = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int listBackground = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int listBackgroundLight = 2131165190;
			
			// aapt resource value: 0x7f070009
			public const int notificationColor = 2131165193;
			
			// aapt resource value: 0x7f070007
			public const int primaryLabelColor = 2131165191;
			
			// aapt resource value: 0x7f070008
			public const int textInputColor = 2131165192;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f080005
			public const int card_menu_button_height = 2131230725;
			
			// aapt resource value: 0x7f080007
			public const int card_menu_button_margin_side = 2131230727;
			
			// aapt resource value: 0x7f080008
			public const int card_menu_button_margin_top = 2131230728;
			
			// aapt resource value: 0x7f080006
			public const int card_menu_button_width = 2131230726;
			
			// aapt resource value: 0x7f080002
			public const int font_size_label_large = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int font_size_label_medium = 2131230723;
			
			// aapt resource value: 0x7f080001
			public const int font_size_label_xlarge = 2131230721;
			
			// aapt resource value: 0x7f080000
			public const int font_size_label_xxlarge = 2131230720;
			
			// aapt resource value: 0x7f080004
			public const int indeterminate_progress_size = 2131230724;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ab_background_textured_busidexactionbar = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ab_bottom_solid_busidexactionbar = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ab_solid_busidexactionbar = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ab_stacked_solid_busidexactionbar = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ab_texture_tile_busidexactionbar = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ab_transparent_busidexactionbar = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int add = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int add2 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int background_blur5 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int border = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int browser = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int btn_cab_done_busidexactionbar = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int btn_cab_done_default_busidexactionbar = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int btn_cab_done_focused_busidexactionbar = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int btn_cab_done_pressed_busidexactionbar = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int busidex_logo_hor = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int button = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int button_cancel = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int cab_background_bottom_busidexactionbar = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int cab_background_top_busidexactionbar = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int cards_back2 = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int checkmark = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int contacts = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int contacts2 = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int contacts_64x64 = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int default_photo_64x64 = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int defaultprofile = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int delete = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int delete2 = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int edit = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int email = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int @event = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int EventIcon = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int EventIconDisabled = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int Exit = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int faq = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int fb = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int home = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int Icon = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int Icon_2x = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int large_logo = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int list_focused_busidexactionbar = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int list_pressed_busidexactionbar = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int logo = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int logo3 = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int main_blur2 = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int MainButtonStyle = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int maps = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int menu_dropdown_panel_busidexactionbar = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int MyBusidexIcon = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int MyBusidexIconDisabled = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int notes = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int notification = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int NotificationDisabled = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int NotificationSimple = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int options = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int OrganizationsIcon = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int OrganizationsIconDisabled = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int people = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int phone = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int profile2_blur = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int profile_background_1 = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public const int progress_bg_busidexactionbar = 2130837566;
			
			// aapt resource value: 0x7f02003f
			public const int progress_horizontal_busidexactionbar = 2130837567;
			
			// aapt resource value: 0x7f020040
			public const int progress_primary_busidexactionbar = 2130837568;
			
			// aapt resource value: 0x7f020041
			public const int progress_secondary_busidexactionbar = 2130837569;
			
			// aapt resource value: 0x7f020042
			public const int puzzle_background = 2130837570;
			
			// aapt resource value: 0x7f020043
			public const int red_minus = 2130837571;
			
			// aapt resource value: 0x7f020044
			public const int refresh = 2130837572;
			
			// aapt resource value: 0x7f020045
			public const int remove = 2130837573;
			
			// aapt resource value: 0x7f020046
			public const int rotate = 2130837574;
			
			// aapt resource value: 0x7f020047
			public const int search_64x64 = 2130837575;
			
			// aapt resource value: 0x7f020048
			public const int SearchIcon = 2130837576;
			
			// aapt resource value: 0x7f020049
			public const int SearchIconDisabled = 2130837577;
			
			// aapt resource value: 0x7f02004a
			public const int selectable_background_busidexactionbar = 2130837578;
			
			// aapt resource value: 0x7f02004b
			public const int settings = 2130837579;
			
			// aapt resource value: 0x7f02004c
			public const int settingsDisabled = 2130837580;
			
			// aapt resource value: 0x7f02004d
			public const int share = 2130837581;
			
			// aapt resource value: 0x7f02004e
			public const int ShareIcon = 2130837582;
			
			// aapt resource value: 0x7f02004f
			public const int spinner_ab_default_busidexactionbar = 2130837583;
			
			// aapt resource value: 0x7f020050
			public const int spinner_ab_disabled_busidexactionbar = 2130837584;
			
			// aapt resource value: 0x7f020051
			public const int spinner_ab_focused_busidexactionbar = 2130837585;
			
			// aapt resource value: 0x7f020052
			public const int spinner_ab_pressed_busidexactionbar = 2130837586;
			
			// aapt resource value: 0x7f020053
			public const int spinner_background_ab_busidexactionbar = 2130837587;
			
			// aapt resource value: 0x7f020054
			public const int splash = 2130837588;
			
			// aapt resource value: 0x7f020055
			public const int splash2 = 2130837589;
			
			// aapt resource value: 0x7f020056
			public const int spotlight_icon = 2130837590;
			
			// aapt resource value: 0x7f020057
			public const int swipe_down = 2130837591;
			
			// aapt resource value: 0x7f020058
			public const int swipe_right = 2130837592;
			
			// aapt resource value: 0x7f020059
			public const int sync = 2130837593;
			
			// aapt resource value: 0x7f02005a
			public const int tab_indicator_ab_busidexactionbar = 2130837594;
			
			// aapt resource value: 0x7f02005b
			public const int tab_selected_busidexactionbar = 2130837595;
			
			// aapt resource value: 0x7f02005c
			public const int tab_selected_focused_busidexactionbar = 2130837596;
			
			// aapt resource value: 0x7f02005d
			public const int tab_selected_pressed_busidexactionbar = 2130837597;
			
			// aapt resource value: 0x7f02005e
			public const int tab_unselected_busidexactionbar = 2130837598;
			
			// aapt resource value: 0x7f02005f
			public const int tab_unselected_focused_busidexactionbar = 2130837599;
			
			// aapt resource value: 0x7f020060
			public const int tab_unselected_pressed_busidexactionbar = 2130837600;
			
			// aapt resource value: 0x7f020061
			public const int tags_64x64 = 2130837601;
			
			// aapt resource value: 0x7f020062
			public const int textmessage = 2130837602;
			
			// aapt resource value: 0x7f020063
			public const int twitter = 2130837603;
			
			// aapt resource value: 0x7f020064
			public const int underline = 2130837604;
			
			// aapt resource value: 0x7f020065
			public const int visibility_64x64 = 2130837605;
			
			// aapt resource value: 0x7f020066
			public const int white_underline = 2130837606;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0a0095
			public const int MyBusidexLayout = 2131361941;
			
			// aapt resource value: 0x7f0a00f8
			public const int btnAccept = 2131362040;
			
			// aapt resource value: 0x7f0a0022
			public const int btnAddPhoneNumber = 2131361826;
			
			// aapt resource value: 0x7f0a0055
			public const int btnAddressInfo = 2131361877;
			
			// aapt resource value: 0x7f0a000f
			public const int btnBack = 2131361807;
			
			// aapt resource value: 0x7f0a002a
			public const int btnCancel = 2131361834;
			
			// aapt resource value: 0x7f0a003a
			public const int btnCancelPicture = 2131361850;
			
			// aapt resource value: 0x7f0a0036
			public const int btnCardBack = 2131361846;
			
			// aapt resource value: 0x7f0a0035
			public const int btnCardFront = 2131361845;
			
			// aapt resource value: 0x7f0a003f
			public const int btnCardImage = 2131361855;
			
			// aapt resource value: 0x7f0a002e
			public const int btnCardImageHor = 2131361838;
			
			// aapt resource value: 0x7f0a0031
			public const int btnCardImageVer = 2131361841;
			
			// aapt resource value: 0x7f0a0073
			public const int btnClose = 2131361907;
			
			// aapt resource value: 0x7f0a00ff
			public const int btnConnect = 2131362047;
			
			// aapt resource value: 0x7f0a0048
			public const int btnContactInfo = 2131361864;
			
			// aapt resource value: 0x7f0a006f
			public const int btnContactListHideInfo = 2131361903;
			
			// aapt resource value: 0x7f0a00e5
			public const int btnContacts = 2131362021;
			
			// aapt resource value: 0x7f0a00f9
			public const int btnDecline = 2131362041;
			
			// aapt resource value: 0x7f0a005a
			public const int btnDeletePhoneNumber = 2131361882;
			
			// aapt resource value: 0x7f0a00d9
			public const int btnEditCard = 2131362009;
			
			// aapt resource value: 0x7f0a0059
			public const int btnEditPhoneNumber = 2131361881;
			
			// aapt resource value: 0x7f0a00ad
			public const int btnEmail = 2131361965;
			
			// aapt resource value: 0x7f0a0079
			public const int btnEventTag = 2131361913;
			
			// aapt resource value: 0x7f0a0082
			public const int btnEvents = 2131361922;
			
			// aapt resource value: 0x7f0a0090
			public const int btnForgotPassword = 2131361936;
			
			// aapt resource value: 0x7f0a0001
			public const int btnHideInfo = 2131361793;
			
			// aapt resource value: 0x7f0a006d
			public const int btnHideProfile = 2131361901;
			
			// aapt resource value: 0x7f0a0107
			public const int btnInfo = 2131362055;
			
			// aapt resource value: 0x7f0a008f
			public const int btnLogin = 2131361935;
			
			// aapt resource value: 0x7f0a00d7
			public const int btnLogout = 2131362007;
			
			// aapt resource value: 0x7f0a007e
			public const int btnMyBusidex = 2131361918;
			
			// aapt resource value: 0x7f0a0080
			public const int btnMyOrganizations = 2131361920;
			
			// aapt resource value: 0x7f0a00b4
			public const int btnOrgMembers = 2131361972;
			
			// aapt resource value: 0x7f0a00b5
			public const int btnOrgReferrals = 2131361973;
			
			// aapt resource value: 0x7f0a00b2
			public const int btnOrganizationFacebook = 2131361970;
			
			// aapt resource value: 0x7f0a00b1
			public const int btnOrganizationTwitter = 2131361969;
			
			// aapt resource value: 0x7f0a00b0
			public const int btnOrganizationWeb = 2131361968;
			
			// aapt resource value: 0x7f0a000d
			public const int btnPanelAdd = 2131361805;
			
			// aapt resource value: 0x7f0a0009
			public const int btnPanelBrowser = 2131361801;
			
			// aapt resource value: 0x7f0a0008
			public const int btnPanelEmail = 2131361800;
			
			// aapt resource value: 0x7f0a0006
			public const int btnPanelMap = 2131361798;
			
			// aapt resource value: 0x7f0a0007
			public const int btnPanelNotes = 2131361799;
			
			// aapt resource value: 0x7f0a000a
			public const int btnPanelPhone = 2131361802;
			
			// aapt resource value: 0x7f0a000c
			public const int btnPanelRemove = 2131361804;
			
			// aapt resource value: 0x7f0a000b
			public const int btnPanelShare = 2131361803;
			
			// aapt resource value: 0x7f0a00ae
			public const int btnPhone = 2131361966;
			
			// aapt resource value: 0x7f0a00c1
			public const int btnPhoneNumber = 2131361985;
			
			// aapt resource value: 0x7f0a00d8
			public const int btnPrivacy = 2131362008;
			
			// aapt resource value: 0x7f0a0018
			public const int btnSave = 2131361816;
			
			// aapt resource value: 0x7f0a00a1
			public const int btnSaveNotes = 2131361953;
			
			// aapt resource value: 0x7f0a0029
			public const int btnSavePhoneNumber = 2131361833;
			
			// aapt resource value: 0x7f0a00d6
			public const int btnSaveProfile = 2131362006;
			
			// aapt resource value: 0x7f0a007c
			public const int btnSearch = 2131361916;
			
			// aapt resource value: 0x7f0a004c
			public const int btnSearchInfo = 2131361868;
			
			// aapt resource value: 0x7f0a0039
			public const int btnSelectPicture = 2131361849;
			
			// aapt resource value: 0x7f0a0085
			public const int btnSettingsHome = 2131361925;
			
			// aapt resource value: 0x7f0a0084
			public const int btnShare = 2131361924;
			
			// aapt resource value: 0x7f0a00ec
			public const int btnShareCard = 2131362028;
			
			// aapt resource value: 0x7f0a0086
			public const int btnSharedCardsNotification = 2131361926;
			
			// aapt resource value: 0x7f0a0101
			public const int btnStart = 2131362049;
			
			// aapt resource value: 0x7f0a0051
			public const int btnTags = 2131361873;
			
			// aapt resource value: 0x7f0a0038
			public const int btnTakePicture = 2131361848;
			
			// aapt resource value: 0x7f0a00c5
			public const int btnTermsAndConditions = 2131361989;
			
			// aapt resource value: 0x7f0a00c2
			public const int btnTextMessage = 2131361986;
			
			// aapt resource value: 0x7f0a0043
			public const int btnVisibility = 2131361859;
			
			// aapt resource value: 0x7f0a001e
			public const int contactInfoContainer = 2131361822;
			
			// aapt resource value: 0x7f0a0020
			public const int contactListViewTitle = 2131361824;
			
			// aapt resource value: 0x7f0a006a
			public const int contactPhoneNumberEntryLayout = 2131361898;
			
			// aapt resource value: 0x7f0a003b
			public const int containerGroup1 = 2131361851;
			
			// aapt resource value: 0x7f0a0044
			public const int containerGroup2 = 2131361860;
			
			// aapt resource value: 0x7f0a004d
			public const int containerGroup3 = 2131361869;
			
			// aapt resource value: 0x7f0a001c
			public const int emailContainer = 2131361820;
			
			// aapt resource value: 0x7f0a0075
			public const int eventCardsProgressStatus = 2131361909;
			
			// aapt resource value: 0x7f0a0077
			public const int eventProgressStatus = 2131361911;
			
			// aapt resource value: 0x7f0a0093
			public const int fragment_holder = 2131361939;
			
			// aapt resource value: 0x7f0a007a
			public const int homeLayout = 2131361914;
			
			// aapt resource value: 0x7f0a0088
			public const int homeProgressContainer = 2131361928;
			
			// aapt resource value: 0x7f0a0037
			public const int imageSelectOptions = 2131361847;
			
			// aapt resource value: 0x7f0a002c
			public const int imageWrapperHor = 2131361836;
			
			// aapt resource value: 0x7f0a002f
			public const int imageWrapperVer = 2131361839;
			
			// aapt resource value: 0x7f0a00d2
			public const int imgAcceptTerms = 2131362002;
			
			// aapt resource value: 0x7f0a0053
			public const int imgAddressInfo = 2131361875;
			
			// aapt resource value: 0x7f0a0052
			public const int imgAddressInfoContainer = 2131361874;
			
			// aapt resource value: 0x7f0a007d
			public const int imgBusidexIcon = 2131361917;
			
			// aapt resource value: 0x7f0a000e
			public const int imgCardDetail = 2131361806;
			
			// aapt resource value: 0x7f0a0105
			public const int imgCardHorizontal = 2131362053;
			
			// aapt resource value: 0x7f0a0106
			public const int imgCardVertical = 2131362054;
			
			// aapt resource value: 0x7f0a00e8
			public const int imgCheckShared = 2131362024;
			
			// aapt resource value: 0x7f0a0068
			public const int imgContact = 2131361896;
			
			// aapt resource value: 0x7f0a003d
			public const int imgEditCardImage = 2131361853;
			
			// aapt resource value: 0x7f0a003c
			public const int imgEditCardImageContainer = 2131361852;
			
			// aapt resource value: 0x7f0a0046
			public const int imgEditContactInfo = 2131361862;
			
			// aapt resource value: 0x7f0a0045
			public const int imgEditContactInfoContainer = 2131361861;
			
			// aapt resource value: 0x7f0a0081
			public const int imgEventIcon = 2131361921;
			
			// aapt resource value: 0x7f0a0102
			public const int imgLoginLogo = 2131362050;
			
			// aapt resource value: 0x7f0a0091
			public const int imgLogo = 2131361937;
			
			// aapt resource value: 0x7f0a00f0
			public const int imgNoNotifications = 2131362032;
			
			// aapt resource value: 0x7f0a00a3
			public const int imgNotesCardHorizontal = 2131361955;
			
			// aapt resource value: 0x7f0a00a4
			public const int imgNotesCardVertical = 2131361956;
			
			// aapt resource value: 0x7f0a00a2
			public const int imgNotesSaved = 2131361954;
			
			// aapt resource value: 0x7f0a007f
			public const int imgOrgIcon = 2131361919;
			
			// aapt resource value: 0x7f0a00b7
			public const int imgOrganizationHeaderImage = 2131361975;
			
			// aapt resource value: 0x7f0a00bb
			public const int imgOrganizationThumbnail = 2131361979;
			
			// aapt resource value: 0x7f0a0004
			public const int imgPanelCardPreviewH = 2131361796;
			
			// aapt resource value: 0x7f0a0005
			public const int imgPanelCardPreviewV = 2131361797;
			
			// aapt resource value: 0x7f0a00be
			public const int imgPhoneCardHorizontal = 2131361982;
			
			// aapt resource value: 0x7f0a00bf
			public const int imgPhoneCardVertical = 2131361983;
			
			// aapt resource value: 0x7f0a002d
			public const int imgPlaceholderHor = 2131361837;
			
			// aapt resource value: 0x7f0a0030
			public const int imgPlaceholderVer = 2131361840;
			
			// aapt resource value: 0x7f0a00ce
			public const int imgProfileEmailSaved = 2131361998;
			
			// aapt resource value: 0x7f0a00cf
			public const int imgProfilePasswordSaved = 2131361999;
			
			// aapt resource value: 0x7f0a00db
			public const int imgQuickShareCardHorizontal = 2131362011;
			
			// aapt resource value: 0x7f0a00dc
			public const int imgQuickShareCardVertical = 2131362012;
			
			// aapt resource value: 0x7f0a009c
			public const int imgRefreshOrganizations = 2131361948;
			
			// aapt resource value: 0x7f0a00fa
			public const int imgResults = 2131362042;
			
			// aapt resource value: 0x7f0a004a
			public const int imgSeachInfo = 2131361866;
			
			// aapt resource value: 0x7f0a0049
			public const int imgSeachInfoContainer = 2131361865;
			
			// aapt resource value: 0x7f0a007b
			public const int imgSearchIcon = 2131361915;
			
			// aapt resource value: 0x7f0a00ed
			public const int imgShareHorizontal = 2131362029;
			
			// aapt resource value: 0x7f0a0083
			public const int imgShareIcon = 2131361923;
			
			// aapt resource value: 0x7f0a00ef
			public const int imgShareVertical = 2131362031;
			
			// aapt resource value: 0x7f0a00f6
			public const int imgSharedCardHorizontal = 2131362038;
			
			// aapt resource value: 0x7f0a00f7
			public const int imgSharedCardVertical = 2131362039;
			
			// aapt resource value: 0x7f0a00fb
			public const int imgSplashLogo = 2131362043;
			
			// aapt resource value: 0x7f0a00a5
			public const int imgTabIcon = 2131361957;
			
			// aapt resource value: 0x7f0a004f
			public const int imgTags = 2131361871;
			
			// aapt resource value: 0x7f0a004e
			public const int imgTagsContainer = 2131361870;
			
			// aapt resource value: 0x7f0a0041
			public const int imgVisibility = 2131361857;
			
			// aapt resource value: 0x7f0a0040
			public const int imgVisibilityContainer = 2131361856;
			
			// aapt resource value: 0x7f0a00a7
			public const int ingOrgDetailLogoBanner = 2131361959;
			
			// aapt resource value: 0x7f0a0025
			public const int innerContainer = 2131361829;
			
			// aapt resource value: 0x7f0a00fc
			public const int layout_start = 2131362044;
			
			// aapt resource value: 0x7f0a00fe
			public const int lblAlreadyAUser = 2131362046;
			
			// aapt resource value: 0x7f0a006c
			public const int lblContactPhoneNumber = 2131361900;
			
			// aapt resource value: 0x7f0a006b
			public const int lblContactPhoneNumberType = 2131361899;
			
			// aapt resource value: 0x7f0a00a8
			public const int lblContacts = 2131361960;
			
			// aapt resource value: 0x7f0a00a9
			public const int lblEmail = 2131361961;
			
			// aapt resource value: 0x7f0a00d0
			public const int lblEmailError = 2131362000;
			
			// aapt resource value: 0x7f0a0072
			public const int lblEventDescription = 2131361906;
			
			// aapt resource value: 0x7f0a00ab
			public const int lblFax = 2131361963;
			
			// aapt resource value: 0x7f0a00fd
			public const int lblIntro = 2131362045;
			
			// aapt resource value: 0x7f0a0100
			public const int lblNewUser = 2131362048;
			
			// aapt resource value: 0x7f0a0098
			public const int lblNoCardsMessage = 2131361944;
			
			// aapt resource value: 0x7f0a00f1
			public const int lblNoNotificationsMessage = 2131362033;
			
			// aapt resource value: 0x7f0a009b
			public const int lblNoOrganizationsMessage = 2131361947;
			
			// aapt resource value: 0x7f0a008c
			public const int lblPassword = 2131361932;
			
			// aapt resource value: 0x7f0a00d1
			public const int lblPasswordError = 2131362001;
			
			// aapt resource value: 0x7f0a00aa
			public const int lblPhone = 2131361962;
			
			// aapt resource value: 0x7f0a0058
			public const int lblPhoneNumber = 2131361880;
			
			// aapt resource value: 0x7f0a0057
			public const int lblPhoneNumberType = 2131361879;
			
			// aapt resource value: 0x7f0a0074
			public const int lblPrivateEventMessage = 2131361908;
			
			// aapt resource value: 0x7f0a00ca
			public const int lblProfileEmail = 2131361994;
			
			// aapt resource value: 0x7f0a00c7
			public const int lblProfileHeader = 2131361991;
			
			// aapt resource value: 0x7f0a00cc
			public const int lblProfilePassword = 2131361996;
			
			// aapt resource value: 0x7f0a00ee
			public const int lblShareError = 2131362030;
			
			// aapt resource value: 0x7f0a00e9
			public const int lblShareFrom = 2131362025;
			
			// aapt resource value: 0x7f0a00e6
			public const int lblShareOR = 2131362022;
			
			// aapt resource value: 0x7f0a00e2
			public const int lblShareTitle = 2131362018;
			
			// aapt resource value: 0x7f0a00e3
			public const int lblShareTo = 2131362019;
			
			// aapt resource value: 0x7f0a008a
			public const int lblUserName = 2131361930;
			
			// aapt resource value: 0x7f0a0104
			public const int listItemLayout = 2131362052;
			
			// aapt resource value: 0x7f0a0089
			public const int loginLayout = 2131361929;
			
			// aapt resource value: 0x7f0a00d3
			public const int lotAcceptTerms = 2131362003;
			
			// aapt resource value: 0x7f0a0023
			public const int lstCardPhoneNumbers = 2131361827;
			
			// aapt resource value: 0x7f0a009a
			public const int lstCards = 2131361946;
			
			// aapt resource value: 0x7f0a006e
			public const int lstContactPhoneNumbers = 2131361902;
			
			// aapt resource value: 0x7f0a0071
			public const int lstContacts = 2131361905;
			
			// aapt resource value: 0x7f0a0076
			public const int lstEventCards = 2131361910;
			
			// aapt resource value: 0x7f0a0078
			public const int lstEvents = 2131361912;
			
			// aapt resource value: 0x7f0a00b9
			public const int lstOrganizationCards = 2131361977;
			
			// aapt resource value: 0x7f0a009e
			public const int lstOrganizations = 2131361950;
			
			// aapt resource value: 0x7f0a00c0
			public const int lstPhoneNumbers = 2131361984;
			
			// aapt resource value: 0x7f0a00e0
			public const int lstSearchResults = 2131362016;
			
			// aapt resource value: 0x7f0a00f2
			public const int lstSharedCards = 2131362034;
			
			// aapt resource value: 0x7f0a0092
			public const int mainLayout = 2131361938;
			
			// aapt resource value: 0x7f0a0099
			public const int myBusidexProgressStatus = 2131361945;
			
			// aapt resource value: 0x7f0a0024
			public const int newPhoneNumberContainer = 2131361828;
			
			// aapt resource value: 0x7f0a00ba
			public const int orgLayout = 2131361978;
			
			// aapt resource value: 0x7f0a00b6
			public const int orgMemberLayout = 2131361974;
			
			// aapt resource value: 0x7f0a00a6
			public const int organizationLayout = 2131361958;
			
			// aapt resource value: 0x7f0a0094
			public const int pager = 2131361940;
			
			// aapt resource value: 0x7f0a0096
			public const int panelHolder = 2131361942;
			
			// aapt resource value: 0x7f0a0000
			public const int panelLayout = 2131361792;
			
			// aapt resource value: 0x7f0a00bd
			public const int phoneLayout = 2131361981;
			
			// aapt resource value: 0x7f0a0056
			public const int phoneNumberEntryLayout = 2131361878;
			
			// aapt resource value: 0x7f0a00da
			public const int profileCover = 2131362010;
			
			// aapt resource value: 0x7f0a00c6
			public const int profileFragment = 2131361990;
			
			// aapt resource value: 0x7f0a00c9
			public const int profileLayout = 2131361993;
			
			// aapt resource value: 0x7f0a001a
			public const int progressBar1 = 2131361818;
			
			// aapt resource value: 0x7f0a009d
			public const int progressBar2 = 2131361949;
			
			// aapt resource value: 0x7f0a00de
			public const int progressBar3 = 2131362014;
			
			// aapt resource value: 0x7f0a0064
			public const int rdoGroupVisibility = 2131361892;
			
			// aapt resource value: 0x7f0a0033
			public const int rdoHorizontal = 2131361843;
			
			// aapt resource value: 0x7f0a0032
			public const int rdoOrientation = 2131361842;
			
			// aapt resource value: 0x7f0a0067
			public const int rdoPrivate = 2131361895;
			
			// aapt resource value: 0x7f0a0065
			public const int rdoPublic = 2131361893;
			
			// aapt resource value: 0x7f0a0066
			public const int rdoSemiPrivate = 2131361894;
			
			// aapt resource value: 0x7f0a0034
			public const int rdoVertical = 2131361844;
			
			// aapt resource value: 0x7f0a009f
			public const int relativeLayout1 = 2131361951;
			
			// aapt resource value: 0x7f0a00e1
			public const int shareCardLayout = 2131362017;
			
			// aapt resource value: 0x7f0a00f3
			public const int sharedCardListItemLayout = 2131362035;
			
			// aapt resource value: 0x7f0a0026
			public const int spnPhoneNumberType = 2131361830;
			
			// aapt resource value: 0x7f0a0017
			public const int spnState = 2131361815;
			
			// aapt resource value: 0x7f0a00d4
			public const int txtAcceptTerms = 2131362004;
			
			// aapt resource value: 0x7f0a0012
			public const int txtAddress1 = 2131361810;
			
			// aapt resource value: 0x7f0a0013
			public const int txtAddress2 = 2131361811;
			
			// aapt resource value: 0x7f0a0054
			public const int txtAddressInfoLabel = 2131361876;
			
			// aapt resource value: 0x7f0a003e
			public const int txtCardImageLabel = 2131361854;
			
			// aapt resource value: 0x7f0a0014
			public const int txtCity = 2131361812;
			
			// aapt resource value: 0x7f0a0003
			public const int txtCompanyName = 2131361795;
			
			// aapt resource value: 0x7f0a0069
			public const int txtContactDisplayName = 2131361897;
			
			// aapt resource value: 0x7f0a0047
			public const int txtContactInfoLabel = 2131361863;
			
			// aapt resource value: 0x7f0a0070
			public const int txtContactListHeader = 2131361904;
			
			// aapt resource value: 0x7f0a00ac
			public const int txtContacts = 2131361964;
			
			// aapt resource value: 0x7f0a0011
			public const int txtDescription = 2131361809;
			
			// aapt resource value: 0x7f0a001d
			public const int txtEmail = 2131361821;
			
			// aapt resource value: 0x7f0a0028
			public const int txtExtension = 2131361832;
			
			// aapt resource value: 0x7f0a00af
			public const int txtFax = 2131361967;
			
			// aapt resource value: 0x7f0a0097
			public const int txtFilter = 2131361943;
			
			// aapt resource value: 0x7f0a008e
			public const int txtLoginFailed = 2131361934;
			
			// aapt resource value: 0x7f0a0002
			public const int txtName = 2131361794;
			
			// aapt resource value: 0x7f0a0027
			public const int txtNewPhoneNumber = 2131361831;
			
			// aapt resource value: 0x7f0a00a0
			public const int txtNotes = 2131361952;
			
			// aapt resource value: 0x7f0a0087
			public const int txtNotificationCount = 2131361927;
			
			// aapt resource value: 0x7f0a00bc
			public const int txtOrganizationName = 2131361980;
			
			// aapt resource value: 0x7f0a001b
			public const int txtPageTitle = 2131361819;
			
			// aapt resource value: 0x7f0a008d
			public const int txtPassword = 2131361933;
			
			// aapt resource value: 0x7f0a0021
			public const int txtPhoneNumbersTitle = 2131361825;
			
			// aapt resource value: 0x7f0a00c8
			public const int txtProfileDescription = 2131361992;
			
			// aapt resource value: 0x7f0a00cb
			public const int txtProfileEmail = 2131361995;
			
			// aapt resource value: 0x7f0a00cd
			public const int txtProfilePassword = 2131361997;
			
			// aapt resource value: 0x7f0a00dd
			public const int txtQuickShareMessage = 2131362013;
			
			// aapt resource value: 0x7f0a00df
			public const int txtSearch = 2131362015;
			
			// aapt resource value: 0x7f0a002b
			public const int txtSearchInfoDescription = 2131361835;
			
			// aapt resource value: 0x7f0a004b
			public const int txtSearchInfoLabel = 2131361867;
			
			// aapt resource value: 0x7f0a0010
			public const int txtSearchInfoTitle = 2131361808;
			
			// aapt resource value: 0x7f0a00b8
			public const int txtSearchOrgMembers = 2131361976;
			
			// aapt resource value: 0x7f0a00ea
			public const int txtShareDisplayName = 2131362026;
			
			// aapt resource value: 0x7f0a00e7
			public const int txtShareEmail = 2131362023;
			
			// aapt resource value: 0x7f0a00eb
			public const int txtShareMessage = 2131362027;
			
			// aapt resource value: 0x7f0a00e4
			public const int txtSharePhoneNumber = 2131362020;
			
			// aapt resource value: 0x7f0a00f5
			public const int txtSharedCardCompanyName = 2131362037;
			
			// aapt resource value: 0x7f0a00f4
			public const int txtSharedCardName = 2131362036;
			
			// aapt resource value: 0x7f0a00c3
			public const int txtSpinnerText = 2131361987;
			
			// aapt resource value: 0x7f0a005d
			public const int txtTag1 = 2131361885;
			
			// aapt resource value: 0x7f0a005e
			public const int txtTag2 = 2131361886;
			
			// aapt resource value: 0x7f0a005f
			public const int txtTag3 = 2131361887;
			
			// aapt resource value: 0x7f0a0060
			public const int txtTag4 = 2131361888;
			
			// aapt resource value: 0x7f0a0061
			public const int txtTag5 = 2131361889;
			
			// aapt resource value: 0x7f0a0062
			public const int txtTag6 = 2131361890;
			
			// aapt resource value: 0x7f0a0063
			public const int txtTag7 = 2131361891;
			
			// aapt resource value: 0x7f0a0050
			public const int txtTagsLabel = 2131361872;
			
			// aapt resource value: 0x7f0a005c
			public const int txtTitle = 2131361884;
			
			// aapt resource value: 0x7f0a001f
			public const int txtUrl = 2131361823;
			
			// aapt resource value: 0x7f0a008b
			public const int txtUserName = 2131361931;
			
			// aapt resource value: 0x7f0a00d5
			public const int txtViewTerms = 2131362005;
			
			// aapt resource value: 0x7f0a0042
			public const int txtVisibilityLabel = 2131361858;
			
			// aapt resource value: 0x7f0a005b
			public const int txtYourName = 2131361883;
			
			// aapt resource value: 0x7f0a0016
			public const int txtZip = 2131361814;
			
			// aapt resource value: 0x7f0a0019
			public const int updateCover = 2131361817;
			
			// aapt resource value: 0x7f0a00c4
			public const int vwPrivacy = 2131361988;
			
			// aapt resource value: 0x7f0a0103
			public const int vwTerms = 2131362051;
			
			// aapt resource value: 0x7f0a00b3
			public const int vwWeb = 2131361971;
			
			// aapt resource value: 0x7f0a0015
			public const int zipStateContainer = 2131361813;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ButtonPanel = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Card = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int CardAddressInfo = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int CardContactInfo = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int CardImageEdit = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int CardMenu = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int CardPhoneNumber = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int CardSearchInfo = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int CardTags = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int CardVisibility = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int ContactListItem = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int ContactPhoneNumberEntry = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int ContactProfile = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int Contacts = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int EventCards = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int EventList = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int EventListListItem = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int Home = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int ListGroup = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int Login = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int Main = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int MyBusidex = 2130903061;
			
			// aapt resource value: 0x7f030016
			public const int MyOrganizations = 2130903062;
			
			// aapt resource value: 0x7f030017
			public const int Notes = 2130903063;
			
			// aapt resource value: 0x7f030018
			public const int notification = 2130903064;
			
			// aapt resource value: 0x7f030019
			public const int OptionsTab = 2130903065;
			
			// aapt resource value: 0x7f03001a
			public const int Organization = 2130903066;
			
			// aapt resource value: 0x7f03001b
			public const int OrganizationCards = 2130903067;
			
			// aapt resource value: 0x7f03001c
			public const int OrganizationListItem = 2130903068;
			
			// aapt resource value: 0x7f03001d
			public const int Phone = 2130903069;
			
			// aapt resource value: 0x7f03001e
			public const int PhoneNumberEntry = 2130903070;
			
			// aapt resource value: 0x7f03001f
			public const int PhoneTypeSpinnerItem = 2130903071;
			
			// aapt resource value: 0x7f030020
			public const int PrivacyPolicy = 2130903072;
			
			// aapt resource value: 0x7f030021
			public const int Profile = 2130903073;
			
			// aapt resource value: 0x7f030022
			public const int QuickShare = 2130903074;
			
			// aapt resource value: 0x7f030023
			public const int Search = 2130903075;
			
			// aapt resource value: 0x7f030024
			public const int SharedCard = 2130903076;
			
			// aapt resource value: 0x7f030025
			public const int SharedCardList = 2130903077;
			
			// aapt resource value: 0x7f030026
			public const int SharedCardListItem = 2130903078;
			
			// aapt resource value: 0x7f030027
			public const int Splash = 2130903079;
			
			// aapt resource value: 0x7f030028
			public const int StartUp = 2130903080;
			
			// aapt resource value: 0x7f030029
			public const int StateSpinnerItem = 2130903081;
			
			// aapt resource value: 0x7f03002a
			public const int tab = 2130903082;
			
			// aapt resource value: 0x7f03002b
			public const int TermsAndConditions = 2130903083;
			
			// aapt resource value: 0x7f03002c
			public const int UserCardListItem = 2130903084;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int ApplicationName = 2131099649;
			
			// aapt resource value: 0x7f060008
			public const int EventList_PrivateMessage = 2131099656;
			
			// aapt resource value: 0x7f06001b
			public const int Global_ButtonText_Cancel = 2131099675;
			
			// aapt resource value: 0x7f06001a
			public const int Global_ButtonText_Logout = 2131099674;
			
			// aapt resource value: 0x7f060012
			public const int Global_ButtonText_Ok = 2131099666;
			
			// aapt resource value: 0x7f060016
			public const int Global_LoadingCards = 2131099670;
			
			// aapt resource value: 0x7f060018
			public const int Global_LoadingCardsProgress = 2131099672;
			
			// aapt resource value: 0x7f060017
			public const int Global_LoadingEvent = 2131099671;
			
			// aapt resource value: 0x7f060019
			public const int Global_LoggingYouIn = 2131099673;
			
			// aapt resource value: 0x7f060014
			public const int Global_Logout_Message = 2131099668;
			
			// aapt resource value: 0x7f060013
			public const int Global_Logout_Title = 2131099667;
			
			// aapt resource value: 0x7f060015
			public const int Global_OneMoment = 2131099669;
			
			// aapt resource value: 0x7f06002f
			public const int InsightsApiKey = 2131099695;
			
			// aapt resource value: 0x7f06000f
			public const int Login_btnForgotPassword = 2131099663;
			
			// aapt resource value: 0x7f06000e
			public const int Login_btnLogin = 2131099662;
			
			// aapt resource value: 0x7f06000d
			public const int Login_lblPassword = 2131099661;
			
			// aapt resource value: 0x7f06000c
			public const int Login_lblUserName = 2131099660;
			
			// aapt resource value: 0x7f06000a
			public const int Main_btnMyBusidex = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int Main_btnMyOrganizations = 2131099659;
			
			// aapt resource value: 0x7f060009
			public const int Main_btnSearch = 2131099657;
			
			// aapt resource value: 0x7f060010
			public const int MyBusidex_NoCards = 2131099664;
			
			// aapt resource value: 0x7f060011
			public const int MyOrganizations_NoOrganizations = 2131099665;
			
			// aapt resource value: 0x7f060026
			public const int Notes_Save = 2131099686;
			
			// aapt resource value: 0x7f06001c
			public const int Notifications_NoReferrals = 2131099676;
			
			// aapt resource value: 0x7f060027
			public const int Organization_NoOrganizations = 2131099687;
			
			// aapt resource value: 0x7f060033
			public const int PhoneTypePrompt = 2131099699;
			
			// aapt resource value: 0x7f06002d
			public const int Profile_DescriptionNewAccount = 2131099693;
			
			// aapt resource value: 0x7f06002e
			public const int Profile_DescriptionUpdateAccount = 2131099694;
			
			// aapt resource value: 0x7f06002b
			public const int Profile_ErrorAccountExists = 2131099691;
			
			// aapt resource value: 0x7f06002c
			public const int Profile_ErrorAccountGeneral = 2131099692;
			
			// aapt resource value: 0x7f060029
			public const int Profile_ErrorEmailGeneral = 2131099689;
			
			// aapt resource value: 0x7f060028
			public const int Profile_ErrorEmailInUse = 2131099688;
			
			// aapt resource value: 0x7f06002a
			public const int Profile_ErrorUnableToCreateAccount = 2131099690;
			
			// aapt resource value: 0x7f060030
			public const int QuickShareMessage = 2131099696;
			
			// aapt resource value: 0x7f060023
			public const int Share_ConfirmAccept = 2131099683;
			
			// aapt resource value: 0x7f060024
			public const int Share_ConfirmDecline = 2131099684;
			
			// aapt resource value: 0x7f060021
			public const int Share_ConfirmShareTitleAccept = 2131099681;
			
			// aapt resource value: 0x7f060022
			public const int Share_ConfirmShareTitleDecline = 2131099682;
			
			// aapt resource value: 0x7f06001e
			public const int Share_Description = 2131099678;
			
			// aapt resource value: 0x7f060020
			public const int Share_Error = 2131099680;
			
			// aapt resource value: 0x7f060025
			public const int Share_ErrorCardNotAdded = 2131099685;
			
			// aapt resource value: 0x7f06001f
			public const int Share_ShareCard = 2131099679;
			
			// aapt resource value: 0x7f06001d
			public const int Share_Title = 2131099677;
			
			// aapt resource value: 0x7f060005
			public const int StartPage_btnConnect = 2131099653;
			
			// aapt resource value: 0x7f060007
			public const int StartPage_btnStart = 2131099655;
			
			// aapt resource value: 0x7f060004
			public const int StartPage_lblAlreadyAUser = 2131099652;
			
			// aapt resource value: 0x7f060006
			public const int StartPage_lblNewUser = 2131099654;
			
			// aapt resource value: 0x7f060003
			public const int StartPage_lblWelcome = 2131099651;
			
			// aapt resource value: 0x7f060032
			public const int StateSpinnerPropmt = 2131099698;
			
			// aapt resource value: 0x7f060034
			public const int app_loading = 2131099700;
			
			// aapt resource value: 0x7f060002
			public const int app_name = 2131099650;
			
			// aapt resource value: 0x7f060036
			public const int button_update_later = 2131099702;
			
			// aapt resource value: 0x7f060035
			public const int button_update_now = 2131099701;
			
			// aapt resource value: 0x7f060000
			public const int library_name = 2131099648;
			
			// aapt resource value: 0x7f060031
			public const int quickshare = 2131099697;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f090004
			public const int ActionBar_Solid_Busidexactionbar = 2131296260;
			
			// aapt resource value: 0x7f090005
			public const int ActionBar_Transparent_Busidexactionbar = 2131296261;
			
			// aapt resource value: 0x7f090008
			public const int ActionBarTabStyle_Busidexactionbar = 2131296264;
			
			// aapt resource value: 0x7f09000b
			public const int ActionButton_CloseMode_Busidexactionbar = 2131296267;
			
			// aapt resource value: 0x7f09000d
			public const int CardMenuButton = 2131296269;
			
			// aapt resource value: 0x7f090003
			public const int CustomThemeActionBarTitleTextStyle = 2131296259;
			
			// aapt resource value: 0x7f090007
			public const int DropDownListView_Busidexactionbar = 2131296263;
			
			// aapt resource value: 0x7f090009
			public const int DropDownNav_Busidexactionbar = 2131296265;
			
			// aapt resource value: 0x7f090006
			public const int PopupMenu_Busidexactionbar = 2131296262;
			
			// aapt resource value: 0x7f09000a
			public const int ProgressBar_Busidexactionbar = 2131296266;
			
			// aapt resource value: 0x7f090001
			public const int SearchBar = 2131296257;
			
			// aapt resource value: 0x7f090002
			public const int Theme_Busidexactionbar = 2131296258;
			
			// aapt resource value: 0x7f09000c
			public const int Theme_Busidexactionbar_Widget = 2131296268;
			
			// aapt resource value: 0x7f090000
			public const int Theme_Splash = 2131296256;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] CircleImageView = new int[]
			{
					2130771968,
					2130771969,
					2130771970,
					2130771971};
			
			// aapt resource value: 1
			public const int CircleImageView_civ_border_color = 1;
			
			// aapt resource value: 2
			public const int CircleImageView_civ_border_overlay = 2;
			
			// aapt resource value: 0
			public const int CircleImageView_civ_border_width = 0;
			
			// aapt resource value: 3
			public const int CircleImageView_civ_fill_color = 3;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
